import { Product } from "./columns";

export const data: Product[] = [
  {
    id: "1",
    description: "🤑🔥🕘Аренда Вип Сервера | 24 часа🕒🔥🤑, VIP-сервер",
    count: 322,
    price: 0.64,
    hot: true,
    pinned: true,
    seller: {
      id: "1",
      name: "0xHearts.com",
      avatar: "/1.png",
      rating: 4.9,
      isOnline: true,
      timeOnSite: "3 года на сайте",
      contOfRreviews: "4288 отзывов",
    },
  },
  {
    id: "2",
    description:
      "❤ФРУКТ СПИРИТ, СПИРИТ, БЛОКС ФРУКТ, SPIRIT💛💢, Предметы, Трейд",
    count: -1,
    price: 0.63,
    hot: false,
    pinned: false,
    seller: {
      id: "2",
      name: "IgorDun4enkoff",
      avatar: "/2.png",
      rating: 2.0,
      isOnline: true,
      timeOnSite: "1 год на сайте",
      contOfRreviews: "45 отзывов",
    },
  },
  {
    id: "3",
    description:
      "🤲Куплю и пройду рейд БУДДЫ - БУДДА РЕЙД - БУДА - место будды - Рейды буды - BUDDHA RAID - 🤲, Услуги",
    count: 4556,
    price: 0.6,
    hot: false,
    pinned: false,
    seller: {
      id: "3",
      name: "Dendi",
      avatar: "/3.png",
      rating: 5.0,
      isOnline: false,
      timeOnSite: "2 дня на сайте",
      contOfRreviews: "4 отзыва",
    },
  },
  {
    id: "4",
    description:
      "🍩 / Рейд Теста - Куплю и пройду рейд Теста - РЕЙДЫ ТЕСТА - МЕСТО ТЕСТА - ДОУЧ - 🍩, Услуги",
    count: 15666,
    price: 0.55,
    hot: false,
    pinned: false,
    seller: {
      id: "4",
      name: "qewbie",
      avatar: "/4.png",
      rating: 1.0,
      isOnline: true,
      timeOnSite: "5 лет на сайте",
      contOfRreviews: "200 отзывов",
    },
  },
  {
    id: "5",
    description: "💛Фрукт Будда 💛 🟡Buddha Fruit🟡, Предметы, Трейд",
    count: 104242,
    price: 0.55,
    hot: false,
    pinned: false,
    seller: {
      id: "4",
      name: "qewbie",
      avatar: "/4.png",
      rating: 3.0,
      isOnline: true,
      timeOnSite: "5 лет на сайте",
      contOfRreviews: "200 отзывов",
    },
  },
  {
    id: "6",
    description: "🧠spirit fruit | Спирит | фрукт Спирит🧠, Предметы, Трейд",
    count: 322,
    price: 0.64,
    hot: false,
    pinned: false,
    seller: {
      id: "6",
      name: "0xHearts.com",
      avatar: "/1.png",
      rating: 4.9,
      isOnline: true,
      timeOnSite: "3 года на сайте",
      contOfRreviews: "4288 отзывов",
    },
  },
  {
    id: "7",
    description: "🟦Rumble Fruit🟦Фрукт Грохот, Предметы, Трейд",
    count: -1,
    price: 0.63,
    hot: false,
    pinned: false,
    seller: {
      id: "7",
      name: "IgorDun4enkoff",
      avatar: "/2.png",
      rating: 2.1,
      isOnline: true,
      timeOnSite: "1 год на сайте",
      contOfRreviews: "45 отзывов",
    },
  },
  {
    id: "8",
    description: "🐘 Фрукт Мамонта 🐘 Мамонт/Mammoth 🐘, Предметы, Трейд",
    count: 1502410,
    price: 0.6,
    hot: false,
    pinned: false,
    seller: {
      id: "8",
      name: "Dendi",
      avatar: "/3.png",
      rating: 4.9,
      isOnline: false,
      timeOnSite: "2 дня на сайте",
      contOfRreviews: "4 отзыва",
    },
  },
  {
    id: "9",
    description:
      "🔑 🔪  Заспавню и убью катакури в1 / Получение бледного шарфа / бледный шарф  🔪 🔑, Услуги",
    count: 15666,
    price: 0.55,
    hot: false,
    pinned: false,
    seller: {
      id: "9",
      name: "qewbie",
      avatar: "/4.png",
      rating: 3.6,
      isOnline: true,
      timeOnSite: "5 лет на сайте",
      contOfRreviews: "200 отзывов",
    },
  },
  {
    id: "10",
    description:
      "👾Призову / Убью(если надо) рип индру / активирую все плиты / Rip_indra / rip_indra / выбью чашу👾, Услуги",
    count: 15666,
    price: 0.55,
    hot: false,
    pinned: false,
    seller: {
      id: "10",
      name: "qewbie",
      avatar: "/4.png",
      rating: 3.6,
      isOnline: true,
      timeOnSite: "5 лет на сайте",
      contOfRreviews: "200 отзывов",
    },
  },
  {
    id: "11",
    description:
      "🔑👑 Заспавню и убью катакури в2 / Получение рейда теста / миррор фрактал / зеркальный фрактал /👑🔑, Услуги",
    count: -1,
    price: 0.63,
    hot: false,
    pinned: false,
    seller: {
      id: "11",
      name: "IgorDun4enkoff",
      avatar: "/1.png",
      rating: 2.1,
      isOnline: true,
      timeOnSite: "1 год на сайте",
      contOfRreviews: "45 отзывов",
    },
  },
  {
    id: "12",
    description:
      "⚔️ КУПЛЮ И ПРОЙДУ ЛО - БОСС ЛО - ЛО - РЕЙД ЛО - ЧИП ЛО - БУСТ - RAID LO - LO - ⚔️, Услуги",
    count: 15666,
    price: 0.55,
    hot: false,
    pinned: false,
    seller: {
      id: "12",
      name: "qewbie",
      avatar: "/2.png",
      rating: 3.6,
      isOnline: true,
      timeOnSite: "5 лет на сайте",
      contOfRreviews: "200 отзывов",
    },
  },
  {
    id: "13",
    description: "Вандо, Услуги",
    count: 1502410,
    price: 0.6,
    hot: false,
    pinned: false,
    seller: {
      id: "13",
      name: "Dendi",
      avatar: "/3.png",
      rating: 4.9,
      isOnline: false,
      timeOnSite: "2 дня на сайте",
      contOfRreviews: "4 отзыва",
    },
  },
  {
    id: "14",
    description: "✨🍀Прокачка LvL цена за 1 уровень🍀✨, Услуги",
    count: 15666,
    price: 0.55,
    hot: false,
    pinned: false,
    seller: {
      id: "14",
      name: "qewbie",
      avatar: "/4.png",
      rating: 3.6,
      isOnline: true,
      timeOnSite: "5 лет на сайте",
      contOfRreviews: "200 отзывов",
    },
  },
  {
    id: "15",
    description:
      "💝Набор 3 в 1 Покупка Легендарных мечей 💝 wando / shisui / saddi / ТТК / TTK / Вандо / Шисуи/ Садди, Услуги",
    count: 104242,
    price: 0.55,
    hot: false,
    pinned: false,
    seller: {
      id: "15",
      name: "qewbie",
      avatar: "/4.png",
      rating: 3.6,
      isOnline: true,
      timeOnSite: "5 лет на сайте",
      contOfRreviews: "200 отзывов",
    },
  },
];
